Create db user profile
uwcsc/codeybot pull request #155
Opened 2022-02-05 22:38 UTC by smilesthesad

# Related Issues
resolves <https://github.com/uwcsc/codeybot/issues/139>

# Summary of Changes 
Added user profile database

# Steps to Reproduce
Create the database, try inserting things in

2022-02-06 21:52 UTC, gzcharleszhang commented on src/components/profile.ts
> +export const initUserProfileTable = async (db: Database): Promise<void> => {
I think @Picowchew recently moved all the init table stuff to `db.ts`, so we should follow that convention too

2022-02-06 22:08 UTC, marko-polo-cheno requested changes

2022-02-06 22:08 UTC, marko-polo-cheno commented on src/components/db.ts
> +import { initSuggestionsTable } from './suggestions';
ya i may have done smth here to fix a conflict, but plz pull latest bc the format of db.ts changed to avoid cyclic imports

2022-02-07 03:37 UTC, marko-polo-cheno approved these changes
LGTM :)
The only thing I would suggest changing is ``user_table`` to ``user_profile_table`` bc 'profile' is more descriptive compared to 'user'.

Keep in mind that the fields in ``user_table`` are bound to change in the future.
Feel free to merge as well as self-assign another ticket. Do lmk if u ever need more details tho.

2022-02-08 05:37 UTC, merged