added aliases and embed message inlining for user profiles
uwcsc/codeybot pull request #205
Opened 2022-05-08 02:49 UTC by smilesthesad

# Related Issues
resolves <https://github.com/uwcsc/codeybot/issues/189>
Issue(s) that this PR will resolve, e.g. "resolves <issue link here>".

# Summary of Changes 
Previously user profile was very vertical. some fields do not need to take up an entire row. Also, I added the userprofile alias and made profile about the default command.

# Steps to Reproduce
Set up your user profile (.profile set <field> <description>) for multiple fields. Check out that it is not as vertical anymore.
Previous
<img width="247" alt="image" src="https://user-images.githubusercontent.com/36215359/167279594-936f1efc-3c5e-41f8-8e99-445fabd0115c.png">

New
<img width="658" alt="image" src="https://user-images.githubusercontent.com/36215359/167279602-2581d31a-7950-49c0-b812-bc41398bf263.png">

List the steps needed for the reviewer to produce your PR changes.

2022-05-08 02:51 UTC, marko-polo-cheno commented on src/commands/profile/profile.ts
> +        profileDisplay.addField(prettyProfileDetails.last_updated, profileDetails['last_updated'], true)
semi

2022-05-08 02:52 UTC, marko-polo-cheno requested changes
plz check github action stuff

2022-05-08 02:52 UTC, marko-polo-cheno commented
also screenshots as proof of QA

2022-05-08 03:28 UTC, marko-polo-cheno requested changes
i sorri

2022-05-08 03:28 UTC, marko-polo-cheno commented on src/commands/profile/profile.ts
>    public async about(message: Message, args: Args): Promise<Message> {
could move this enum to components
prettyProfileDetails

2022-05-08 03:28 UTC, marko-polo-cheno commented on src/commands/profile/profile.ts
> +          if (key === 'about_me') {
hmm i wonder if enum[WORD] could replace 'word'.
or, const notInLine = ['about_me', etc.] (mayhaps in components)
better practice idk?

2022-05-08 03:28 UTC, marko-polo-cheno commented on src/commands/profile/profile.ts
> +      const notDisplay = ['user_id', 'last_updated'];
mayhaps in components?

2022-05-09 03:36 UTC, alexz429 requested changes

2022-05-09 03:36 UTC, alexz429 commented on src/commands/profile/profile.ts
> +              val.toString(),
nitpick, but you can probably pass in 
`key !== 'about_me'` 
or something into the inline param so that you don't need an if/else

2022-05-09 03:37 UTC, alexz429 commented
Not sure if this should be a separate issue, but do we want to enable the about to default to the caller's profile?

So if they just do
`.aboutme` 
It should realize they just want their own profile and show it.

2022-05-12 05:44 UTC, marko-polo-cheno approved these changes

2022-05-12 05:44 UTC, merged