Added help command
uwcsc/codeybot pull request #224
Opened 2022-07-07 04:27 UTC by Picowchew

# Related Issues

Resolves #223 

# Summary of Changes

Added the help command that provides the URL to the wiki page

# Steps to Reproduce

`.help` and `.wiki` should work (as well as their slash command version)

2022-07-07 14:36 UTC, alexz429 requested changes
one nit, otherwise LGTM

2022-07-11 17:42 UTC, marko-polo-cheno commented
in future, makes pr reviewer life easier if you put a screenshot in here so we may not have to physically test
:)

![image](https://user-images.githubusercontent.com/37851975/178325096-fcb29c2d-c97f-4441-b646-83be986084bd.png)
question tho, why is it "edited"

2022-07-11 17:42 UTC, marko-polo-cheno approved these changes

2022-07-12 00:55 UTC, alexz429 approved these changes

2022-07-12 05:51 UTC, Picowchew commented
The edited message should be fixed by https://github.com/uwcsc/codeybot/pull/232.

2022-07-12 05:51 UTC, merged