added Moderator tag to ban message in messageCreate.ts
uwcsc/codeybot pull request #235
Opened 2022-07-12 20:51 UTC by WWW0030

# Related Issues

# Summary of Changes

# Steps to Reproduce

2022-07-15 21:59 UTC, Picowchew requested changes
Good start! I have a few comments.

It would be nice if you could fill out the PR description. There are comments in the PR template to describe what is meant to be written in each section. This makes it much easier for the reviewer to go through your PR. For instance, I was actually confused at first as to the purpose of this PR; was it supposed to DM the banned person with the moderator for them to contact or was it supposed to log which moderator (or Codey) did the banning. I later received clarification that you are working on this ticket https://github.com/uwcsc/codeybot/issues/185, so in the "Related Issues" section, you can do something like `Resolves #185` to automatically close the issue when the PR is merged (https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

I believe that what the code currently does is that in the log message (which is sent in the server) that is only accessible by mods and executives, the username and discriminator of a mod is added to the reason. What should be done instead is that the banned person should receive a DM from Codey with a ping to a mod. In this way, the banned person would be able to contact a mod after leaving the server due to the ban. The reason why a ping is used is that the banned person can easily click on the ping and then message the mod. If they do not have any mutual servers though, then from the ping, the username and discriminator can be obtained, and then from this information, the banned person is able to send the mod a friend request. After accepting the friend request, the banned person is able to message the mod. The coffee chat code DMs people with a ping, so feel free to look there for some guidance on how this could be done. In addition, as described in the issue, you can add the ID of the mod as another config variable as opposed to making the username and discriminator a constant within the file. This allows for easier changing of the mod.

Feel free to reply here if you have any questions!

2022-07-16 17:16 UTC, alexz429 requested changes

2022-07-16 17:16 UTC, alexz429 commented on src/listeners/messageCreate.ts
> +      const reason = 'Spammer/troll/got hacked'+'for appeal, please contact: '+APPEAL_MODERATOR_ID;
make sure this looks right when you test it, there doesn't seem to be a space between hacked and for

2022-07-16 17:16 UTC, alexz429 commented on src/listeners/messageCreate.ts
>  const ANNOUNCEMENTS_CHANNEL_ID: string = vars.ANNOUNCEMENTS_CHANNEL_ID;
check these linting errors, typically if you installed a linter into your IDE these should be autofixed.

2022-08-18 14:01 UTC, mcpenguin commented
Any updates on this?

2022-08-23 02:28 UTC, mcpenguin commented
Closing this PR due to inactivity.

2022-08-23 02:28 UTC, closed without merging