changed time to 1 min for update + channel id for office status
uwcsc/codeybot pull request #245
Opened 2022-07-16 18:36 UTC by danielk1345

- Changed time to 1 min for status update
- Made new channel in public server named "office-status"
- changed prod config file to include channel id

2022-07-16 18:54 UTC, alexz429 requested changes
delete the package-lock and office channel id and we're good

2022-07-16 18:54 UTC, alexz429 commented on config/production/vars.json
> +  "OFFICE_CHANNEL_ID": "943680816880447488",
if we are using office_status_channel_id, we don't need office_channel_id anymore

2022-07-16 19:02 UTC, alexz429 approved these changes
LGTM

2022-07-17 03:57 UTC, marko-polo-cheno approved these changes

2022-07-18 01:26 UTC, merged