Exclude bots from leaderboard
uwcsc/codeybot pull request #281
Opened 2022-08-12 22:45 UTC by KevinBacabac

https://github.com/uwcsc/codeybot/issues/265

I don't have a database to test this ticket

2022-08-13 01:14 UTC, Picowchew reviewed
In terms of not having a database, shouldn't SQLite be installed due to being found in yarn.lock?

2022-08-13 01:38 UTC, Picowchew commented
I might as well add that the change would be taking place in the messageCreate listener instead of the leaderboard, since bots shouldn't have a coin balance *at all*. Bots not appearing in the leaderboard would just be one effect of this.

2022-08-13 03:07 UTC, Picowchew commented
The issue has been updated just now for clearer specifications; sorry about that!

2022-08-13 03:35 UTC, KevinBacabac commented
No problem it's ready to test

2022-08-14 02:51 UTC, Picowchew requested changes

2022-08-14 02:51 UTC, Picowchew commented on src/listeners/messageCreate.ts
>      }
This case can be removed, since it is already covered below.

2022-08-14 02:53 UTC, Picowchew commented
Also, do you mind adding 275813801792634880 as IRC_USER_ID for staging and updating README.md for the new config variable IRC_USER_ID?

2022-08-14 03:10 UTC, Picowchew approved these changes
LGTM!

2022-08-14 03:10 UTC, merged