feat: Allow adding components to commands
uwcsc/codeybot pull request #327
Opened 2022-08-18 00:16 UTC by hydrobeam

## Summary of Changes

Added components field where needed and imported types.
Added checks in run functions to see if the message contains a component, if so then do not executeCommand.

Using components requires placing the required components in a file under `src/interaction-handlers` as per the sapphire framework: https://www.sapphirejs.dev/docs/Guide/application-commands/interaction-handlers/what-are-they

## Motivation and Explanation

Components can do cool things, like implement SelectMenus + other interactions:

https://discordjs.guide/interactions/select-menus.html#building-and-sending-select-menus

## Related Issues

N/A

## Steps to Reproduce

N/A

## Demonstration of Changes

See #304 `/interviewer domain` for a showcase of an implementation 

## Further Information and Comments

2022-08-18 13:48 UTC, mcpenguin requested changes
This is a little weird, but if it works, it works

2022-08-18 13:48 UTC, mcpenguin commented on src/codeyCommand.ts
> +  components?: (MessageActionRow | (Required<BaseMessageComponentOptions> & MessageActionRowOptions))[] = [];
Extract `MessageActionRow | (Required<BaseMessageComponentOptions> & MessageActionRowOptions))` into a `CodeyComponent` type, and use that here? That way if the component class ever changes, we can just change that.

2022-08-18 14:11 UTC, hydrobeam commented
> This is a little weird, but if it works, it works


Yeah taking another look at this implementation and after having worked on #329, it doesn't really make sense for `components` to be treated any differently from embeds. So `executeCommand` should be used to generate the component, and then the actual managing of the resonse should be done in the `run` method under the exported class in `interaction-handlers`. 

My approach in #304 was to have `interaction-handlers` call back to `executeCommand`, which is weird and doesn't follow the trend established by other commands.  Would be worth introducing an optional `componentHandler` function or something like that to keep the logic centralized.

2022-08-18 14:43 UTC, mcpenguin commented
I think a `ComponentHandler`, or even a more generic `Handler` class would be good to centralize the logic, as you mentioned. In the future, as part of desapphirication of the interaction handler, we could employ the observer pattern or something similar (haha CS246 go brrrr) to register listeners for interactions for responding to components. That is outside the scope of this ticket though - I think making a handler is the right way to go here.

2022-08-24 00:05 UTC, mcpenguin commented
Closing - PR is not needed anymore

2022-08-24 00:05 UTC, closed without merging