Introduced pdf preview deletion in the resume channel
uwcsc/codeybot pull request #407
Opened 2022-11-14 03:23 UTC by saad-a-li

## Summary of Changes
Introduced resume pdf preview deletion when the original message is deleted.

## Motivation and Explanation
Provides a added level of enhancement and privacy to the resume channel.

## Steps to Reproduce
Send a pdf to your bot's channel and delete the message you sent after the preview shows up.

## Further Information and Comments

2022-11-14 14:57 UTC, Picowchew requested changes
Nice clean code that you wrote so far! :)

Currently, if someone with the permission to delete messages deletes the image preview, and then the PDF file gets deleted, then the bot would crash. To solve this issue, if the image preview gets deleted, then the entry in the database can be removed as well.

In addition, we can remove the entry in the database if the PDF file (and consequently, the image preview as well) gets deleted.

The PR is also not passing build due to linting and formatting. Try `yarn lint` and `yarn format`.

2022-11-14 14:57 UTC, Picowchew commented on src/events/messageDelete.ts
> +    return;
This `return` statement seems to be redundant and can be removed.

2022-12-19 00:47 UTC, Picowchew requested changes

2022-12-19 00:47 UTC, Picowchew commented on src/components/db.ts
> +};
Because we now query by `preview_id`, we can create an index on `preview_id`.

2022-12-21 00:35 UTC, Picowchew approved these changes
I left one small comment. Other than that, LGTM! Nice work! :)

2022-12-21 00:35 UTC, Picowchew commented on src/components/db.ts
> +  await db.run('CREATE INDEX IF NOT EXISTS ix_preview_id ON resume_preview_info (preview_id)');
Following how the other indices are named, it looks like the index name should be `ix_resume_preview_info_preview_id`.

2023-01-19 05:27 UTC, mcpenguin approved these changes
LGTM!

2023-01-19 06:17 UTC, merged