done
uwcsc/codeybot pull request #411
Opened 2022-11-22 02:43 UTC by smilesthesad

## Summary of Changes

Adds a helper that, given a crunchbase entity id or a crunchbase company page, returns info on the company. Currently returns the following information:
```{
  properties: {
    short_description: 'Vendia is a real-time data cloud, offering a fast and scalable way to share operational data across data silos, clouds, and partners.',
    identifier: {
      uuid: 'b507d77c-5285-4de9-a237-70fe53a46273',
      value: 'Vendia',
      image_id: 'cpuf13twbf75y9bjau7h',
      permalink: 'vendia',
      entity_def_id: 'organization'
    }
  }
}```
## Motivation and Explanation

Works towards <https://github.com/uwcsc/codeybot/issues/122>. Once this is in, we can track companies in our database and start implementing commands.
## Related Issues

Resolves <https://github.com/uwcsc/codeybot/issues/402>. 
## Steps to Reproduce

Call the function through ts-node. 
## Demonstration of Changes

https://user-images.githubusercontent.com/36215359/203208004-0c59cbfa-0f5e-4dd6-894d-d42e004122e6.mov

## Further Information and Comments

2022-11-24 21:12 UTC, Picowchew requested changes
Overall looks good! I just left some very small nitpicks.

2022-11-24 21:12 UTC, Picowchew commented on src/utils/companyinfo.ts
> +  console.log(data);
Just for the sake of making a commit, I believe we can remove this `console.log` statement.

2022-11-24 21:26 UTC, Picowchew requested changes
Oh one more thing, the file `companyinfo.ts` should be renamed to `companyInfo.ts`.

2022-11-24 21:39 UTC, smilesthesad commented on src/utils/companyinfo.ts
> +  // if not, return null
good catch

2022-11-25 00:19 UTC, Picowchew requested changes

2022-11-25 00:19 UTC, Picowchew commented on src/utils/companyinfo.ts
> +  // check if urlPattern matches companyCrunchbaseLink
Isn't this a misplaced comment, since `urlPattern` is found in `isValidUrl`?

2022-11-25 00:36 UTC, Picowchew approved these changes
LGTM!

2022-11-25 03:45 UTC, mcpenguin approved these changes
LGTM too!

2022-11-25 05:27 UTC, merged