424 explicit codey user error
uwcsc/codeybot pull request #441
Opened 2023-02-04 03:22 UTC by probro27

## Summary of Changes
Edited the current returning of messages and errors to return CodeyUserError which is a new class to represent errors that relate to command validation. 

## Motivation and Explanation
It helps differentiate successful messages to failure messages. 

## Related Issues
resolves #424 

## Steps to Reproduce
Need to run all the commands to see if the error received are correct. 

## Demonstration of Changes
<img width="861" alt="image" src="https://user-images.githubusercontent.com/84613574/216745383-2a401ed2-2417-40b8-8113-412c672f2625.png">
<img width="866" alt="image" src="https://user-images.githubusercontent.com/84613574/216745415-495dc84d-6543-49b9-af94-32cdde3ef4b1.png">

## Further Information and Comments
Some place `undefined` has been passed for message in `CodeyUserError`. This is because message has been set during the catch block (as message was not provided in the function itself).

2023-02-04 17:14 UTC, mcpenguin requested changes
Some comments.

2023-02-04 17:14 UTC, mcpenguin commented on src/codeyCommand.ts
> +      throw new CodeyUserError(undefined, `Unknown option type.`);
Actually, we should just change this to a regular Error, since this isn't an error propagated to the user.

2023-02-04 17:14 UTC, mcpenguin commented on src/codeyCommand.ts
> +      console.log(e instanceof CodeyUserError);
remove this debug message?

2023-02-05 04:29 UTC, probro27 commented
@mcpenguin should be good to go

2023-02-06 01:13 UTC, mcpenguin approved these changes
LGTM!

2023-02-06 01:13 UTC, merged