Connect 4!
uwcsc/codeybot pull request #472
Opened 2023-04-08 01:31 UTC by SaurontheMighty

## Summary of Changes
src/commands/games/connectFour.ts: Connect 4 command
src/commandDetails/games/connectFour.ts: Connect 4 command details
src/components/games/connectFour.ts: 
- Game Tracker
   - start a game
   - end a game
- Game: 
   - setStatus which checks for a win and sets status accordingly
   - getGameResponse
   - various helpers
- Connect 4 Game State
   - player ids
   - status
   - columns: array of ConnectFourColumn objects which in turn are arrays of ConnectFourGameSign objects which represent player tokens or pending if nothing there yet
   - winType: set to none at the start otherwise holds info about whether it was a horizontal/vertical/diagonal connect4
src/interaction-handlers/games/connectFour.ts: Interaction handlers for the buttons

## Motivation and Explanation
This PR adds Connect 4 to Codey. More games = better? This PR does not include bet or challenger. The user can simply play against codey who will pick a random column to put its token into.

## Related Issues
resolves #320 

## Steps to Reproduce
N/A

## Demonstration of Changes
<img width="636" alt="image" src="https://user-images.githubusercontent.com/52637731/230697064-ad808bf0-a423-477b-ae23-7d9d195d5d80.png">

## Further Information and Comments

2023-04-08 14:59 UTC, mcpenguin requested changes
Small comment.

2023-04-08 14:59 UTC, mcpenguin commented on src/commandDetails/games/connectFour.ts
> +      name: 'challenger',
Currently, connect4 only supports single player mode. I would remove this parameter for now until multiplayer is supported.

2023-04-12 01:58 UTC, SaurontheMighty commented
> Seems like build is failing because of the linter.

Ah yeah one line I missed, fixed now.

2023-04-13 20:18 UTC, mcpenguin approved these changes
LGTM!

2023-04-14 01:29 UTC, merged