Allow bot to ban users outside server
uwcsc/codeybot pull request #501
Opened 2023-11-20 04:53 UTC by davidgan1218

## Summary of Changes
Allows bot to ban users outside of server even if they have never joined server, previously bot could only ban users already in server.

Note: Ban Message is only sent to banned user if they are already in the server because on Discord direct messages can only be sent to users who are in mutual servers.

2023-11-24 22:36 UTC, Fan-Yang-284 requested changes
Just before merging can you push another commit for a small tweak that we missed before this but might as well fix now - otherwise LGTM!

2023-11-24 22:36 UTC, Fan-Yang-284 commented on src/commandDetails/admin/ban.ts
>          days ? `and deleted their messages in the past ${days} days ` : ``
Here, just update `days` to `${pluralize('day', days)}` like in `src/components/admin.ts/makeBanMessage`

2023-11-24 23:19 UTC, Fan-Yang-284 commented on src/components/admin.ts
> +    days && `and your messages in the past ${days} ${pluralize('day', days)} have been deleted `
Edit: It looks like this won't work as intended if `days` is undefined, so just revert it back to the ternary operator

2023-12-02 22:17 UTC, probro27 submitted a review, later dismissed
@davidgan1218 LGTM! Please do make the changes that Fan mentioned and there are some merge conflicts so please resolve them.

2023-12-06 16:37 UTC, Fan-Yang-284 commented
There still seem to be a few linter errors (pictured below) so just fix those and it'll be good!

![image](https://github.com/uwcsc/codeybot/assets/69977136/a04945ab-0c6c-494f-b2cf-4fb8d1163525)

2023-12-06 16:39 UTC, Fan-Yang-284 approved these changes

2023-12-06 16:42 UTC, merged