Issue #283
uwcsc/codeybot pull request #508
Opened 2024-01-28 03:34 UTC by KuroganeToyama

## Summary of Changes
- Slashified `interviewer` command

## Related Issues
- Resolve #283 

## Notes
- The setup has not been fully tested yet since I need guidance on that. Will get things done soon.

2024-01-28 18:59 UTC, Fan-Yang-284 commented on src/commandDetails/interviewer/clear.ts
> +\`${container.botPrefix}interviewer clear\``,
```suggestion
\`${container.botPrefix}interviewers clear\``,
```

2024-01-28 19:06 UTC, Fan-Yang-284 requested changes
Awesome work! Thanks for working on this - I think just change these two things

- currently the `list` command produces slightly odd-looking output, so just remove the comma created from `.join`
![image](https://github.com/uwcsc/codeybot/assets/69977136/6f3b5c9a-768c-4dea-8d2b-61d650687436)
- maybe modify the description for profile since it only displays information
BTW you can ignore the above suggestion of adding an 's' to the example usage, that was me being dumb and not realising they were aliases.

2024-01-28 19:06 UTC, Fan-Yang-284 commented on src/commandDetails/interviewer/profile.ts
> +  description: 'Modify profile data',
```suggestion
  description: 'Display profile data',
```

2024-01-28 19:06 UTC, Fan-Yang-284 commented on src/commandDetails/interviewer/list.ts
> +    interviewersInfo[0] === undefined ? 'No data to display' : interviewersInfo.join();
```suggestion
    interviewersInfo[0] === undefined ? 'No data to display' : interviewersInfo.join('');
```

2024-01-29 16:51 UTC, Fan-Yang-284 approved these changes

2024-01-29 17:00 UTC, probro27 approved these changes
@KuroganeToyama LGTM! Thank you for figuring this out! The PR is good to go

2024-01-29 17:01 UTC, merged